name: temperament
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_mobx: ^2.3.0
  get_it: ^9.2.0
  get_storage: ^2.1.1
  mobx: ^2.5.0
  mobx_codegen: ^2.7.4

dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/cerebro.png"

flutter:
  uses-material-design: true

  assets:

    - assets/images/
    - assets/icon/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Thin.ttf
          weight: 200
        - asset: assets/fonts/Inter_28pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_28pt-Bold.ttf
          weight: 700
